//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_us
    {
        public int ticket_id { get; set; }
        public System.DateTime create_date { get; set; }
        public string phone_num { get; set; }
        public string e_mail { get; set; }
        public string ticket_text { get; set; }
    }
}
