//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int feedback_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime create_time { get; set; }
        public string feedback_text { get; set; }
    
        public virtual User User { get; set; }
    }
}
